### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by MoNTE48** [tenplus1/boats#1]
I can not use it on Android.
It's weird, because I can open chests and doors short pressing (on_rightclick), but the boat just destroyed.

**Comment by tenplus1** [comment]
Boats work fine for the android users on Xanadu server, are you using the OFFICIAL Minetest game or a clone ??

**Comment by MoNTE48** [comment]
I use official minetest app with minetest_game on master.

**Comment by tenplus1** [comment]
Boats should only be destroyed if you hit land at full speed while riding one...  Here is a link to the latest 0.4.13 build from WaywardOne on the minetest forums, try this and see if it helps:
https://forum.minetest.net/viewtopic.php?f=42&t=12169&hilit=wayward&start=25#p195526

**Comment by MoNTE48** [comment]
Excuse me, it works on the official assembly. Please see the my game. I have a short press and long puts block removes it (as in Minecraft PE). It works with doors, chests, and any objects other than the boat.
